package cmd

import (
	"os"
	"path/filepath"
	"strings"
)

// ruleFileMarker identifies a SkillGod-owned file so re-runs are idempotent and
// so we never overwrite a file at the same path that the user wrote themselves
// (same non-clobber principle as the Claude Code hooks merge, but simpler here
// since these are dedicated, additive files, not a shared config to merge into).
const ruleFileMarker = "Auto-generated by SkillGod (sg init)"

// ruleFileStatus mirrors hookResult's shape for consistent reporting.
type ruleFileStatus struct {
	path   string
	status string // "new" | "skipped" | "foreign"
}

// writeAdditiveRuleFile writes `content` to `path` unless a file already exists
// there. If the existing file carries our marker, it's left alone (idempotent
// re-run). If it exists WITHOUT our marker, it's some other file the user
// placed at that exact path — never overwritten; the caller reports "foreign"
// so the user can see what happened.
func writeAdditiveRuleFile(path, content string) (ruleFileStatus, error) {
	if data, err := os.ReadFile(path); err == nil {
		if strings.Contains(string(data), ruleFileMarker) {
			return ruleFileStatus{path, "skipped"}, nil
		}
		return ruleFileStatus{path, "foreign"}, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return ruleFileStatus{}, err
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return ruleFileStatus{}, err
	}
	return ruleFileStatus{path, "new"}, nil
}

// cursorRuleContent — .mdc format confirmed against Cursor's own docs
// (cursor.com/docs/rules): frontmatter `alwaysApply: true` guarantees inclusion
// in every chat session ("Always included. Globs and description are ignored.").
// Kept short per Cursor's own guidance (always-apply rules cost context on
// every request — keep them under ~200 words).
const cursorRuleContent = `---
alwaysApply: true
---

<!-- ` + ruleFileMarker + `. Do not edit manually — run sg init to regenerate. -->

# SkillGod — Automatic Skill & Memory Injection

Before responding to any coding-related request, call the ` + "`sg_inject_context`" + ` MCP
tool with the user's request as the ` + "`task`" + ` argument, and use its returned context
(relevant skills + project memory) to inform your response.

This applies to every coding request in this project, not just some of them.
`

// windsurfRuleContent — confirmed against Windsurf's docs (via docs.devin.ai,
// Windsurf's current documentation host): workspace rules with
// `trigger: always_on` are unconditionally included, same guarantee class as
// Cursor's alwaysApply. Written to the WORKSPACE-level location
// (.windsurf/rules/), not the global ~/.codeium/windsurf/memories/global_rules.md
// — global is shared across every project on the machine and isn't ours to
// write into; workspace is the correctly-scoped location for a per-project rule.
const windsurfRuleContent = `---
trigger: always_on
---

<!-- ` + ruleFileMarker + `. Do not edit manually — run sg init to regenerate. -->

# SkillGod — Automatic Skill & Memory Injection

Before responding to any coding-related request, call the ` + "`sg_inject_context`" + ` MCP
tool with the user's request as the ` + "`task`" + ` argument, and use its returned context
(relevant skills + project memory) to inform your response.

This applies to every coding request in this project, not just some of them.
`

// devinRuleContent — Windsurf rebranded to "Devin Desktop" (Cognition) on
// 2026-06-02. Current Devin Desktop builds PREFER the .devin/rules/ path, while
// legacy .windsurf/rules/ (and .windsurfrules) are still read during the
// transition. sg init therefore writes BOTH: .devin/rules/ as the preferred
// path going forward, .windsurf/rules/ as the confirmed-still-read fallback, so
// a rule fires whether the user is on an older Windsurf build or a current Devin
// Desktop one. Same `trigger: always_on` schema either way.
const devinRuleContent = windsurfRuleContent

// antigravityRuleContent — Antigravity (Google's agentic IDE) workspace rules
// live at .agent/rules/*.md with frontmatter `trigger: always_on`, the same
// schema Windsurf uses. UNLIKE the Cursor/Windsurf entries above, this was
// NOT verified against a running install — Antigravity's own docs site
// (antigravity.google/docs) is a JS-rendered SPA that couldn't be fetched as
// text, so this is built from converging secondary sources (Google Codelabs,
// developer blog posts) as of July 2026, not a first-party spec confirmed by
// running `sg init` against real Antigravity and observing the rule fire.
// Flag this for re-verification against a live install before relying on it.
const antigravityRuleContent = `---
trigger: always_on
---

<!-- ` + ruleFileMarker + `. Do not edit manually — run sg init to regenerate. -->

# SkillGod — Automatic Skill & Memory Injection

Before responding to any coding-related request, call the ` + "`sg_inject_context`" + ` MCP
tool with the user's request as the ` + "`task`" + ` argument, and use its returned context
(relevant skills + project memory) to inform your response.

This applies to every coding request in this project, not just some of them.
`

// writeCursorRules writes the project-level always-applied rule Cursor
// guarantees delivery of. cwd is the directory `sg init` was run from.
func writeCursorRules(cwd string) (ruleFileStatus, error) {
	path := filepath.Join(cwd, ".cursor", "rules", "skillgod.mdc")
	return writeAdditiveRuleFile(path, cursorRuleContent)
}

// writeWindsurfRules writes the workspace-level always_on rule for
// Windsurf / Devin Desktop. Writes the PREFERRED current path
// (.devin/rules/skillgod.md) first, then the legacy fallback
// (.windsurf/rules/skillgod.md) — both are still read by current builds during
// the Windsurf→Devin Desktop transition, so writing both guarantees the rule
// fires regardless of which build the user is running. Returns a status per
// path written so `sg init` can report both.
func writeWindsurfRules(cwd string) ([]ruleFileStatus, error) {
	var out []ruleFileStatus
	devinPath := filepath.Join(cwd, ".devin", "rules", "skillgod.md")
	ds, err := writeAdditiveRuleFile(devinPath, devinRuleContent)
	if err != nil {
		return out, err
	}
	out = append(out, ds)
	legacyPath := filepath.Join(cwd, ".windsurf", "rules", "skillgod.md")
	ls, err := writeAdditiveRuleFile(legacyPath, windsurfRuleContent)
	if err != nil {
		return out, err
	}
	out = append(out, ls)
	return out, nil
}

// writeAntigravityRules writes the workspace-level always_on rule for
// Antigravity. See antigravityRuleContent's comment — unverified against a
// live install, unlike the Cursor/Windsurf equivalents.
func writeAntigravityRules(cwd string) (ruleFileStatus, error) {
	path := filepath.Join(cwd, ".agent", "rules", "skillgod.md")
	return writeAdditiveRuleFile(path, antigravityRuleContent)
}
